# Generated by Django 4.0.3 on 2022-06-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_profile_ph_pro_profile_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ph_pro',
            field=models.BigIntegerField(default='196878558'),
        ),
    ]
