# Generated by Django 4.0.3 on 2022-06-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_alter_profile_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Not Available', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Not Available', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(default='Not Available', max_length=250),
        ),
    ]
