# Generated by Django 4.0.3 on 2022-06-10 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Register', '0007_rename_profile_profi'),
    ]

    operations = [
        migrations.CreateModel(
            name='prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_pro', models.ImageField(default='default\\default_imgpro.jpg', upload_to='media')),
                ('state', models.CharField(default='Not Available', max_length=250)),
                ('city', models.CharField(default='Not Available', max_length=250)),
                ('street', models.CharField(default='Not Available', max_length=250)),
                ('ph_pro', models.BigIntegerField(default='196878558')),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='profi',
        ),
    ]
