# Generated by Django 4.0.3 on 2022-04-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('discription', models.TextField()),
                ('price', models.IntegerField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='media/SparePartsimage')),
            ],
        ),
    ]
