# Generated by Django 4.0.3 on 2022-04-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_spareparts_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
                ('category_description', models.TextField()),
                ('category_image', models.ImageField(upload_to='media/SparePartsimage')),
                ('category_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
