# Generated by Django 4.0.3 on 2022-04-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.category'),
        ),
    ]
