# Generated by Django 4.0.3 on 2022-05-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_ids', models.CharField(max_length=150)),
                ('product_ids', models.CharField(max_length=150)),
                ('invoice_id', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
                ('processed_on', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
