# Generated by Django 4.0.3 on 2022-05-20 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Register', '0001_initial'),
        ('Home', '0008_rename_card_ids_order_cart_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('rev', models.TextField()),
                ('added', models.DateTimeField(auto_now=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.profile')),
                ('ratpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.spareparts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
