# Generated by Django 4.0.3 on 2022-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rev',
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
