# Generated by Django 4.0.3 on 2022-05-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_feedback_rev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='prof',
        ),
    ]
