# Generated by Django 4.0.3 on 2022-05-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_remove_feedback_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rev',
        ),
    ]
