# Generated by Django 4.0.3 on 2022-05-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_remove_feedback_rev'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
