# Generated by Django 4.0.3 on 2022-05-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_rename_usr_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ratpro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.spareparts'),
            preserve_default=False,
        ),
    ]
