# Generated by Django 4.0.3 on 2022-06-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_whishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='product',
            field=models.CharField(max_length=250),
        ),
    ]
