# Generated by Django 4.2.6 on 2023-12-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contnum',
            field=models.PositiveBigIntegerField(),
        ),
    ]
